# -*- Mode: toml; tab-width: 4; indent-tabs-mode: nil; fill-column: 100 -*-
#
# This file is part of the LibreOffice project.
#
# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.
#

[package]
name = "rust_uno"
version = "0.1.0"
edition = "2024"
description = "Rust FFI binding for LibreOffice UNO API"

[lib]
name = "rust_uno"
crate-type = ["cdylib"]

# vim: set noet sw=4 ts=4:
